config/routes.rb
Obits::Application.routes.draw do
  match 'admin' => redirect('/admin/obituaries')

  resources :obituaries, :only => :index

  namespace(:admin){ resources :obituaries, :except => :show }  
end

app/models/obituary.rb
require 'csv'

class Obituary < ActiveRecord::Base
  default_scope :conditions => { :dirty => false }

  validates_presence_of :last_name, :printed_on

  define_index do
    # fields
    indexes "CONCAT(first_name,' ',middle_name,' ',last_name)", :as => :full_name
    indexes "CONCAT(first_name,' ',last_name)", :as => :name
    indexes last_name, :sortable => true
    indexes first_name, :sortable => true
    indexes other_name

    # attributes
    has died_on

    # properties
    set_property :delta => true
  end
  
  def self.dirty
    with_exclusive_scope { where(:dirty => true) }
  end
  
  def self.import
    data = CSV.read("#{Rails.root}/obits.csv")
    data.shift
    data.each do |row|
      obit = new
      obit.last_name   = row[0].try(:strip)
      obit.middle_name = row[1].try(:strip)
      obit.first_name  = row[2].try(:strip)
      obit.other_name  = row[3].try(:strip)
      obit.born_on     = row[5]
      obit.died_on     = row[7]
      obit.printed_on  = row[17]
      obit.page        = row[18].try(:strip)
      obit.notes       = sanitize_notes(birth_note:row[6],death_note:row[8],
        infant:row[9],location:sanitize_location(row[11],row[12],row[13]),
        maiden_name:row[4])
      obit.dirty       = true if obit.last_name.blank? ||
        obit.printed_on.blank? || obit.page.blank?

      obit.save(false)
    end
  end
  
  def born_on=(value)
    self[:born_on] = Chronic.parse(value).to_date unless value.blank?
  end
  
  def died_on=(value)
    self[:died_on] = Chronic.parse(value).to_date unless value.blank?
  end
  
  def fullname
    fullname ||= ''.tap do |str|
      str << last_name
      first_middle = [first_name,middle_name].compact.join(' ')
      str << ", #{first_middle}" if first_middle.present?
      str << " (#{other_name})" if other_name.present?
    end
  end
  
  def printed_on=(value)
    self[:printed_on] = Chronic.parse(value).to_date unless value.blank?
  end
  
  private
    def self.sanitize_location(city=nil,state=nil,country=nil)
      loc = ''.tap do |s|
        location = [city,state]
        location << country unless country.to_s.gsub(/\W/,'').match(/us/i)
        location = location.compact.join(', ')
        s << location unless location.blank?
      end

      loc.blank? ? nil : loc
    end
  
    def self.sanitize_notes(fields={})
      notes = [].tap do |a|
        fields.reject {|key,value| value.blank? }.each do |key,val|
          a << case key
          when :birth_note
            "born in #{val.strip}" unless val.match(/u[kn|nk]/i)
          when :death_note
            "died in #{val.strip}" unless val.match(/u[kn|nk]/i)
          when :infant
            "infant" if val == 1
          when :location
            val.strip
          when :maiden_name
            "maiden name: #{val.strip}"
          end
        end
      end
      
      notes = notes.compact.join("\n")
      notes.blank? ? nil : notes
    end
end

app/controllers/admin/obituaries_controller.rb
class Admin::ObituariesController < ApplicationController
  before_filter :authorize
  
  layout 'admin'
  
  def index
    @obituaries = Obituary.search(params[:search],search_options).page(params[:page])
  end

  def new
    @obituary = Obituary.new
  end

  def create
    @obituary = Obituary.new(params[:obituary])
    if @obituary.save
      redirect_to admin_obituaries_url, :notice => "Successfully created obituary."
    else
      render :action => 'new'
    end
  end

  def edit
    @obituary = Obituary.find(params[:id])
  end

  def update
    @obituary = Obituary.find(params[:id])
    if @obituary.update_attributes(params[:obituary])
      redirect_to admin_obituaries_url, :notice  => "Successfully updated obituary."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @obituary = Obituary.find(params[:id])
    @obituary.destroy
    redirect_to admin_obituaries_url, :notice => "Successfully destroyed obituary."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :admin?
  
  protected
    def admin?
      controller_path =~ /admin/
    end

    def authorize
      if authenticate_with_http_basic do |username, password|
          username == 'admin' && password == 'deathandtaxes'
        end
      else
        request_http_basic_authentication
      end
    end

    def search_options(options={})
      options.merge({
        :star => true,
        :match_mode => :any,
        :field_weights => {
          :full_name  => 10,
          :name       => 8,
          :last_name  => 6,
          :first_name => 2
        }
      })
    end
end

app/controllers/obituaries_controller.rb
class ObituariesController < ApplicationController
  # GET /obituaries
  def index
    if params[:range].present?
      @range = params[:range].split(",")
      @range = Time.parse(@range.first)..Time.parse(@range.last)
      with = { :died_on => @range }
    end
    order = params[:sort] == 'name' ? 'last_name ASC, first_name ASC' : nil
    @obituaries = Obituary.search(params[:search],search_options(:with => with, :order => order)).page(params[:page])
  end
end

app/helpers/admin/obituaries_helper.rb
module Admin::ObituariesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/obituaries_helper.rb
module ObituariesHelper

  def date_or_unknown(date)
    date.present? ? formatted_date(date) : content_tag(:em,'exact date not known')
  end

  def decipher_date_range(range)
    min, max = range.first, range.last
    case
    when max.year > 2010
      content_tag(:strong,"after 2010")
    when min.year < 1930
      content_tag(:strong,"before 1930")
    else
      "from " + content_tag(:strong,"#{min.year}-#{max.year}")
    end
  end

  def formatted_date(date,format='%B %d, %Y')
    date.strftime(format)
  end

  def options_for_date_range(value)
    options = []
    decade = Date.today.year - Date.today.year % 10
    
    options << ["After #{decade}","#{decade}-01-01,#{Date.today.to_s}"]
    until decade == 1930 do
      decade -= 10
      options << ["#{decade}-#{decade + 9}","#{decade}-01-01,#{decade + 9}-12-31"]
    end
    options << ["Before 1930","#{Obituary.minimum(:died_on).to_s},1929-12-31"]

    options_for_select(options,value)
  end

  def search_text(search,range)
    text = [].tap do |a|
      a << content_tag(:strong,%("#{search}")) if search.present?
      a << decipher_date_range(range) if range.present?
    end
    text.join(' ').html_safe
  end

  def sortable(title,sort=nil)
    link_to title, {:search => params[:search],:range => params[:range],:sort => sort}
  end
end

app/views/admin/obituaries/_form.html.erb
<%= form_for([:admin, @obituary]) do |f| %>
  <%= f.error_messages %>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :other_name %><br />
    <%= f.text_field :other_name %>
  </div>
  <div class="field">
    <%= f.label :printed_on %><br />
    <%= f.text_field :printed_on, :class => 'datepicker' %>
  </div>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :born_on %><br />
    <%= f.text_field :born_on, :class => 'datepicker' %>
  </div>
  <div class="field">
    <%= f.label :died_on %><br />
    <%= f.text_field :died_on, :class => 'datepicker' %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="submit">
    <%= f.submit :class => 'large awesome gray' %>
  </div>
<% end %>

app/views/admin/obituaries/edit.html.erb
<% title "Edit Obituary" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_obituaries_path %></p>

app/views/admin/obituaries/index.html.erb
<div class="actions">
    <%= button_to "Add New Obituary", new_admin_obituary_path, :method => :get, :class => 'large awesome left' %>
    <%= form_tag("/admin/obituaries",:method => :get, :class => 'right') do %>
        <%= text_field_tag :search, params[:search] %> <%= submit_tag 'Search', :class => 'large awesome gray' %>
    <% end %>
</div>
<ul>
    <%= render :partial => 'obituaries/obituary', :collection => @obituaries.compact %>
</ul>
<%= paginate(@obituaries) %>

app/views/admin/obituaries/new.html.erb
<% title "New Obituary" %>

<%= render 'form' %>

<p><%= link_to "Back to List", admin_obituaries_path %></p>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Obits" %></title>
    <%= stylesheet_link_tag "admin" %>
    <%= stylesheet_link_tag "application" %>
    <%= stylesheet_link_tag "smoothness/jquery-ui.css" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:head) %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
      <%= content_tag :h1, yield(:title) if show_title? %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Obits</title>
  <%= stylesheet_link_tag 'application', 'scaffold' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/obituaries/_form.html.erb
<%= form_for(@obituary) do |f| %>
  <% if @obituary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@obituary.errors.count, "error") %> prohibited this obituary from being saved:</h2>

      <ul>
      <% @obituary.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :other_name %><br />
    <%= f.text_field :other_name %>
  </div>
  <div class="field">
    <%= f.label :obituary_printed_on %><br />
    <%= f.date_select :obituary_printed_on %>
  </div>
  <div class="field">
    <%= f.label :page %><br />
    <%= f.text_field :page %>
  </div>
  <div class="field">
    <%= f.label :born_on %><br />
    <%= f.date_select :born_on %>
  </div>
  <div class="field">
    <%= f.label :died_on %><br />
    <%= f.date_select :died_on %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/obituaries/_obituary.html.erb
<li class="<%= cycle('odd','even') %>">
    <strong><%= obituary.fullname %></strong><br/>
    <div class="column results-left">
        <strong>Born:</strong> <%= date_or_unknown(obituary.born_on) %><br />
        <strong>Deceased:</strong> <%= date_or_unknown(obituary.died_on) %><br />
        <strong>Obituary:</strong> <%= formatted_date(obituary.printed_on) %>, <%= obituary.page %><br />
    </div>
    <div class="column results-right">
        <em><%= simple_format(obituary.notes.strip) %></em>
    </div>
    <% if admin? %>
    <p>
        <%= link_to "Edit", edit_admin_obituary_path(obituary) %>
        <%= link_to image_tag('trash.gif'), [:admin, obituary], :confirm => 'Are you sure you want to delete this obituary?', :method => :delete %>
    </p>
    <% end %>
</li>

app/views/obituaries/index.html.erb
<div id="form-wrapper">
    <%= form_tag("/obituaries",:method => :get) do %>
        <div id="name-wrapper" class="field">
            <%= label_tag :search %><br/>
            <%= text_field_tag :search, params[:search] %>
        </div>
        <div id="date-wrapper" class="field">
            <%= label_tag :range, "Date range" %><br/>
            <%= select_tag :range, options_for_date_range(params[:range]), :include_blank => true %>
        </div>
        <%= submit_tag 'Search', :id => 'submit', :class => 'large awesome gray' %>
    <% end %>
</div>
<% if params[:search].present? || @range.present? %>
<h2 id="match">Your search for <%= search_text(params[:search],@range) %> matched <%= @obituaries.search_count %> obituaries.</h2>
<%= sortable("Sort by relevance") %> | <%= sortable("Sort alphabetically", :name) %>
<ul>
    <%= render :partial => 'obituary', :collection => @obituaries.compact %>
</ul>
<%= paginate(@obituaries) %>
<% end %>